[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
clap = "4.5.17"
serde = { version = "1", features = ["derive"]}
envy = "0.4.2"
